name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

    - name: build
      run: make
    
    - name: test
      run: make -I check || true # notice: verification is not fully automated
