name: Test

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        distro: ["ubuntu:latest", "fedora:latest"]
        compiler:
          - { CC: "clang", CXX: "clang++" }
          - { CC: "gcc", CXX: "g++" }
        build_generator:
          - "Unix Makefiles"
        include:
          # Only want to test Ninja on one job
          - distro: "ubuntu:latest"
            compiler: { CC: "clang", CXX: "clang++" }
            build_generator: "Ninja"

    runs-on: ubuntu-latest
    container: ${{ matrix.distro }}
    steps:
    - name: Install Ubuntu dependencies
      if: startsWith(matrix.distro, 'ubuntu')
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt-get update
        apt-get install -y cmake clang gcc git build-essential ninja-build

    - name: Install Fedora dependencies
      if: startsWith(matrix.distro, 'fedora')
      run: dnf --refresh install -y cmake clang gcc git diffutils make

    - uses: actions/checkout@v2

    - name: Install dependencies
      env:
        CC: ${{ matrix.compiler.CC }}
        CXX: ${{ matrix.compiler.CXX }}
      run: |
        mkdir -p deps/prefix && cd deps

        curl -Lfso cxxopts.tar.gz https://github.com/jarro2783/cxxopts/archive/refs/tags/v2.2.1.tar.gz
        echo "984aa3c8917d649b14d7f6277104ce38dd142ce378a9198ec926f03302399681  cxxopts.tar.gz" | sha256sum --check --quiet
        mkdir -p cxxopts/build && tar -xf cxxopts.tar.gz -C cxxopts --strip-components=1
        cd cxxopts/build && cmake -DCMAKE_INSTALL_PREFIX=../../prefix .. && make install -j

        curl -Lfso elfio.tar.gz https://github.com/serge1/ELFIO/releases/download/Release_3.9/elfio-3.9.tar.gz
        echo "767b269063fc35aba6d361139f830aa91c45dc6b77942f082666876c1aa0be0f  elfio.tar.gz" | sha256sum --check --quiet
        mkdir -p elfio/build && tar -xf elfio.tar.gz -C elfio --strip-components=1
        cd elfio/build && cmake -DCMAKE_INSTALL_PREFIX=../../prefix .. && make install -j

        curl -Lfso termcolor.tar.gz https://github.com/ikalnytskyi/termcolor/archive/refs/tags/v2.0.0.tar.gz
        echo "4a73a77053822ca1ed6d4a2af416d31028ec992fb0ffa794af95bd6216bb6a20  termcolor.tar.gz" | sha256sum --check --quiet
        mkdir -p termcolor/build && tar -xf termcolor.tar.gz -C termcolor --strip-components=1
        cd termcolor/build && cmake -DCMAKE_INSTALL_PREFIX=../../prefix .. && make install -j

    - name: Build with ${{ matrix.compiler.CC }}
      env:
        CC: ${{ matrix.compiler.CC }}
        CXX: ${{ matrix.compiler.CXX }}
      run: |
        mkdir build
        cd build
        cmake -G "${{ matrix.build_generator }}" -DLIBTREE_BUILD_TESTING=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_PREFIX_PATH=deps/prefix ..
        cmake --build . -j$(nproc)

    - name: Test
      run: |
        cd build
        ctest --output-on-failure
