name: Test

on: 
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install tools
      run: sudo apt-get update -qq && sudo apt-get install -qq g++-8

    - name: Build
      run: |
          mkdir build 
          cd build 
          CXX=g++-8 cmake -DBUILD_TESTING=ON .. 
          make -j$(nproc)

    - name: Test
      run: |
        cd build
        ctest
           
